<?php if (Mage::helper('ajaxcart')->isModuleEnabled()): ?>
<script type="text/javascript">
    //<![CDATA[
    if (typeof jQuery !== 'undefined') {
        jQuery(document).ready(function(){
        	lsAddCartSettings.init = {
		        ajaxCartEnable = '<?php var_export(Mage::helper('ajaxcart')->isModuleEnabled()); ?>',
		        ajaxCartType = '<?php var_export(Mage::helper('ajaxcart')->getType()); ?>'
	        };
            jQuery(document).ajaxAddToCart(lsAddCartSettings);
        });
    }
    //]]>
</script>
<?php endif;?>