<?php if (Mage::helper('ajaxcart')->isModuleEnabled()): ?>
<script type="text/javascript">
    //<![CDATA[
    if (typeof jQuery !== 'undefined') {
        jQuery(document).ready(function(){
	        var ajaxAddToCart = {
		        init: {
			        ajaxCartEnable: <?php var_export(Mage::helper('ajaxcart')->isModuleEnabled()); ?>,
			        ajaxCartType: <?php var_export(Mage::helper('ajaxcart')->getType()); ?>,
			        isInlineNotificationsEnabled: <?php var_export(Mage::helper('ajaxcart')->isInlineNotificationsEnabled()); ?>
		        }
	        };
            jQuery(document).ajaxAddToCart(ajaxAddToCart);
        });
    }
    //]]>
</script>
<?php endif;?>